### ISSUE TITLE
xiangqi训练代码中棋子价值调整的建议

### ISSUE THREAD

**Issue by ziyue123456789** [ianfab/variant-nnue-pytorch#14]
作者你好，我发现几天前您在（https://github.com/ianfab/variant-nnue-pytorch/tree/xiangqi）这个链接处更新了xiangqi的训练代码，对于代码中的棋子价值设置，我有不同的看法。

我们都知道，在大部分情况下：
棋子"车" 的价值大于两个棋子"炮"的价值
棋子"车" 的价值大于两个棋子"马"的价值
棋子"炮"的价值比棋子"马"的价值大一些
棋子"车" 的价值大于棋子"炮"的价值加上棋子"马"的价值
棋子"相"的价值比棋子"士"的价值大一些

根据我的经验，结合我所浏览的一些资料，我按照比例简单地调整了几个棋子的价值，如下图：
<img width="128" alt="123" src="https://user-images.githubusercontent.com/65974744/170836593-305e9042-3ff3-4ec5-b293-11e33362a4ed.png">

在中国象棋游戏中，有一句谚语"一车相当于十兵"，在我的设置里，一个棋子"兵" 的价值等于150，一个棋子"车" 的价值等于1500，相当于10个兵的价值，我在这里的设置是非常契合的。

我不知道这个调整是否会更好，但如果你之前棋子价值的设置同样是来自于你的手工评估，希望你能考虑我的调整，谢谢你！

**Comment by ianfab** [comment]
The piece values are only used to initialize the network in the beginning. Once you have a network and continue training based on it these values won't be used any more. So overall the exact values used there aren't too relevant.
