### ISSUE TITLE
你好 能不能出一个发行版？

### ISSUE THREAD

**Issue by shuangqiao999** [ianfab/variant-nnue-pytorch#8]
训练工具可以做一个发行版吗？可以让有闲置的硬件资源的玩家自己训练 但是很多玩家不具备编程能力

**Comment by ianfab** [comment]
It would of course be nice to make it easier to train networks, but the dependencies of the training code make it somewhat difficult to achieve that, since the required packages depend on the CUDA version, which in turn depends on the GPU.

**Comment by ianfab** [comment]
I currently do not run any NNUE training, but others do, but we mostly discuss on discord. I assume you can't access discord, so I created https://github.com/ianfab/variant-nnue-pytorch/discussions/13 as a place for those who can't participate on discord. Please share a link to your data there if you want to make it available for others.
